<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Coupon;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    /**
     * Returns an array with coupons inside
     * @param null|string $brand
     * @param null|int $value
     * @param int $limit
     * @return array
     */
    public function getFilteredCoupons($brand = null, $value = null, $limit){
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from(Coupon::class,'c')
            ->orderBy('c.brand','ASC')
            ->setMaxResults($limit);

        if(!is_null($brand) && !is_null($value)){
            $query->where('c.brand = :brand')
                ->setParameter('brand',$brand)
                ->andWhere('c.value = :value')
                ->setParameter('value',$value);
        }else if(!is_null($brand)){
            $query->where('c.brand = :brand')
                ->setParameter('brand',$brand);
        }else if(!is_null($value)){
            $query->where('c.value = :value')
                ->setParameter('value',$value);
        }

        return $query->getQuery()->getArrayResult();
    }
}
